apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: sb-k8s-com-tls
spec:
  secretName: sb-k8s-com
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: sb-k8s.com
  dnsNames:
    - sb-k8s.com
    - www.sb-k8s.com